Use specific MinGW versions instead of MSYS2 MinGW
... to avoid backward compatibility issues with GCC 4-6 MinGW
toolchains.  Apparently GCC 7+ MinGW toolchains introduce a link-time
dependency with internal MinGW CRT functions that are meant to provide
compatibility with Microsoft's Universal CRT (ucrt) library, but those
internal functions are not available in GCC 4-6 MinGW toolchains.  This
made it impossible to use the official builds of libjpeg.a and
libturbojpeg.a with GCC 4-6 MinGW toolchains (a fatal link error--
"undefined reference to '__imp___acrt_iob_func'"-- occurred.)

This problem was not immediately apparent after switching to the MSYS2
implementation of MinGW (6dcf48117b8a378cd592c2176e08e15ae02b7824)
because, for a while, MSYS2 was still using GCC 5 and 6.  Apparently
MSYS2 started using GCC 7 some time before the release of libjpeg-turbo
2.0.1, which is the first release of libjpeg-turbo that ceased being
compatible with GCC 4-6 MinGW toolchains.

Fixes libjpeg-turbo/libjpeg-turbo#382